### ISSUE TITLE
Internal server error when applying filter in Redmine v6.0.1

### ISSUE THREAD

**Issue by PMunch** [happy-se-life/kanban#58]
Recently we set up Redmine running version 6.0.1. I had previously tested out this plugin on the v5.x versions of Redmine and everything seemed to work fine. I added the plugin to our 6.0.1 install and after removing the [`unloadable`](https://github.com/happy-se-life/kanban/blob/master/app/controllers/kanban_controller.rb#L2C3-L2C13) method call from the `KanbanController` it appears to work. However if I try to change any of the filter statuses and hit apply I'm hit with an error:
![2024-11-27T10:22:07](https://github.com/user-attachments/assets/d0cdeb6b-8f0e-4d01-9707-315ce1db7ee3)

The log, when opening a projects Kanban view, setting a different WIP limit in the "Filters" section and hitting apply reads as follows:

```
I, [2024-11-27T09:23:59.047047 #6971]  INFO -- : [8cab8fc9-7dde-463a-bbaf-b710a0c96561] Processing by KanbanController#index as HTML
I, [2024-11-27T09:23:59.047128 #6971]  INFO -- : [8cab8fc9-7dde-463a-bbaf-b710a0c96561]   Parameters: {"updated_within"=>"31", "done_within"=>"14", "due_date"=>"unspecified", "tracker_id"=>"unspecified", "user_id"=>"1", "group_id"=>"unspecified", "project_all"=>"1", "wip_max"=>"1", "card_size"=>"normal_days_left", "cb_ancestor"=>"1", "show_ancestors"=>"1", "status_fields"=>{"1"=>"1", "2"=>"1", "3"=>"1", "4"=>"1", "5"=>"1", "6"=>"0"}, "project_id"=>"iso", "scroll_top"=>"0"}
I, [2024-11-27T09:23:59.050052 #6971]  INFO -- : [8cab8fc9-7dde-463a-bbaf-b710a0c96561]   Current user: admin (id=1)
I, [2024-11-27T09:23:59.074842 #6971]  INFO -- : [8cab8fc9-7dde-463a-bbaf-b710a0c96561]   Rendered layout layouts/base.html.erb (Duration: 18.0ms | GC: 1.0ms)
I, [2024-11-27T09:23:59.075530 #6971]  INFO -- : [8cab8fc9-7dde-463a-bbaf-b710a0c96561] Completed 200 OK in 28ms (Views: 15.9ms | ActiveRecord: 5.5ms (21 queries, 1 cached) | GC: 1.1ms)
F, [2024-11-27T09:23:59.076777 #6971] FATAL -- : [8cab8fc9-7dde-463a-bbaf-b710a0c96561]   
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] TypeError (can't dump IO):
[8cab8fc9-7dde-463a-bbaf-b710a0c96561]   
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] activesupport (7.2.2) lib/active_support/messages/serializer_with_fallback.rb:64:in `dump'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] activesupport (7.2.2) lib/active_support/messages/serializer_with_fallback.rb:64:in `dump'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/cookies.rb:607:in `commit'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/cookies.rb:692:in `commit'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/cookies.rb:530:in `[]='
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/session/cookie_store.rb:117:in `set_cookie'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] rack-session (2.0.0) lib/rack/session/abstract/id.rb:409:in `commit_session'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/session/abstract_store.rb:74:in `commit_session'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] rack-session (2.0.0) lib/rack/session/abstract/id.rb:274:in `context'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/cookies.rb:704:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] activesupport (7.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/callbacks.rb:30:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] railties (7.2.2) lib/rails/rack/logger.rb:41:in `call_app'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] railties (7.2.2) lib/rails/rack/logger.rb:29:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/request_id.rb:33:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] rack (3.1.8) lib/rack/method_override.rb:28:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] rack (3.1.8) lib/rack/runtime.rb:24:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/executor.rb:16:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] actionpack (7.2.2) lib/action_dispatch/middleware/static.rb:27:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] rack (3.1.8) lib/rack/sendfile.rb:114:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] rack (3.1.8) lib/rack/content_length.rb:20:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] railties (7.2.2) lib/rails/engine.rb:535:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] puma (6.4.3) lib/puma/configuration.rb:272:in `call'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] puma (6.4.3) lib/puma/request.rb:100:in `block in handle_request'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] puma (6.4.3) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] puma (6.4.3) lib/puma/request.rb:99:in `handle_request'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] puma (6.4.3) lib/puma/server.rb:464:in `process_client'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] puma (6.4.3) lib/puma/server.rb:245:in `block in run'
[8cab8fc9-7dde-463a-bbaf-b710a0c96561] puma (6.4.3) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

I don't really see anything Kanban specific in that fatal message, but I'm not very familiar with RoR so you might spot something.

I know the v6 line of Redmine isn't officially supported, but neither was the v5 line and it seemed to work well there as I was testing it. I'm wondering if this plugin will get updated to officially support the v6 line, or if we should just look for another light-weight Kanban plugin.

**Comment by happy-se-life** [comment]
When I have some free time, I will also try setting up an environment for version 6.

**Comment by fdigiugno** [comment]
Should be fixed in https://github.com/happy-se-life/kanban/pull/60

**Comment by happy-se-life** [comment]
#60 has been merged.
