### ISSUE TITLE
undefined local variable or method `unloadable' for class KanbanController (NameError)

### ISSUE THREAD

**Issue by ReachableCEO** [happy-se-life/kanban#59]
Dec 04 07:01:50 => Healtheck error: Error: connect ECONNREFUSED 172.18.16.234:3000
Dec 04 07:01:51 - Exiting
Dec 04 07:01:51 - /app/code/plugins/kanban/app/controllers/kanban_controller.rb:2:in `<class:KanbanController>': undefined local variable or method `unloadable' for class KanbanController (NameError)
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 -
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - unloadable
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - ^^^^^^^^^^
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /app/code/plugins/kanban/app/controllers/kanban_controller.rb:1:in `<top (required)>'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:26:in `require'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/cref.rb:60:in `const_get'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/cref.rb:60:in `get'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/eager_load.rb:173:in `block in actual_eager_load_dir'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/helpers.rb:47:in `block in ls'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/helpers.rb:25:in `each'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/helpers.rb:25:in `ls'
Dec 04 07:01:51 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/eager_load.rb:168:in `actual_eager_load_dir'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/eager_load.rb:16:in `each'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader.rb:413:in `block in eager_load_all'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader.rb:411:in `each'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/loader.rb:411:in `eager_load_all'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `instance_exec'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:32:in `run'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:231:in `block in tsort_each'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:353:in `block (2 levels) in each_strongly_connected_component'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:434:in `each_strongly_connected_component_from'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:352:in `block in each_strongly_connected_component'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `call'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:350:in `each_strongly_connected_component'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:229:in `tsort_each'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/tsort.rb:208:in `tsort_each'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/initializable.rb:60:in `run_initializers'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/application.rb:435:in `initialize!'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /app/code/config/environment.rb:16:in `<top (required)>'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from config.ru:3:in `require_relative'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from config.ru:3:in `block (2 levels) in <top (required)>'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `eval'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:108:in `new_from_string'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:97:in `load_file'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rack-3.1.8/lib/rack/builder.rb:67:in `parse_file'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:263:in `app'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:424:in `wrapped_app'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:326:in `block in start'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:382:in `handle_profiling'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/rackup-2.2.1/lib/rackup/server.rb:325:in `start'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/server/server_command.rb:38:in `start'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from <internal:kernel>:90:in `tap'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/server/server_command.rb:136:in `perform'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command/base.rb:178:in `invoke_command'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command/base.rb:73:in `perform'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:71:in `block in invoke'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:149:in `with_argv'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:69:in `invoke'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /run/redmine/vendor/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands.rb:18:in `<top (required)>'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from /home/cloudron/rbenv/versions/3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
Dec 04 07:01:51 <30>1 2024-12-04T07:01:51-06:00 tsys-cloudron b1e03a66-bb9e-4808-aecf-68c518fed0d5 991 b1e03a66-bb9e-4808-aecf-68c518fed0d5 - from bin/rails:4:in `<main>'

**Comment by happy-se-life** [comment]
When I have some free time, I will also try setting up an environment for version 6.

**Comment by happy-se-life** [comment]
@ReachableCEO 

Try latest master branch. This works with version 6.x.

Thanks,

**Comment by ReachableCEO** [comment]
Works great. Thanks! 

Also opened a PR to update the constants.rb path in the README.
